min_version = "0.129.0"
languageCode = "en-us"
title = "Gocrawler Project"

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
  favicon = "favicon.ico"

BookMenuBundle= "/docs/menu"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Gocrawler Project'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
      
  [languages.zh-cn]
    contentDir = 'content/zh-cn'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '中文'
    title = 'Gocrawler爬虫项目'
    weight = 2
    [languages.zh-cn.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
