min_version = "0.129.0"
baseURL = "https://www.go-crawler.com/"
languageCode = "en-us"
title = "Gocrawler Project"

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
  favicon = "favicon.ico"

BookMenuBundle= "/docs/menu"

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true
[languages]

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
      
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Projekt Dokumentation'
    weight = 1
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
